Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
srun: error: frontier04598: tasks 0-7: Exited with exit code 1
srun: Terminating StepId=1437405.0
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
    import gpt as g
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/dbollweg/TMD_work/gpt_utils/qTMD/proton2pttest.py", line 3, in <module>
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
ModuleNotFoundError: No module named 'gpt'
    import gpt as g
ModuleNotFoundError: No module named 'gpt'
srun: error: frontier04734: tasks 56-63: Exited with exit code 1
srun: error: frontier04599: tasks 8-15: Exited with exit code 1
srun: error: frontier04600: tasks 16-23: Exited with exit code 1
srun: error: frontier04601: tasks 24-31: Exited with exit code 1
srun: error: frontier04732: tasks 40-47: Exited with exit code 1
srun: error: frontier04733: tasks 48-55: Exited with exit code 1
srun: error: frontier04603: tasks 32-39: Exited with exit code 1
